import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Booking from '#models/booking'
import User from '#models/user'

export default class extends BaseSeeder {
  async run() {
    const users = await User.query().whereIn('email', [
      'anan.w@tennis.com',
      'krittin.s@tennis.com',
      'nattapong.c@tennis.com',
      'piyawat.r@tennis.com',
      'thanawat.b@tennis.com',
      'supakorn.l@tennis.com',
      'chayut.p@tennis.com',
    ])

    const uid = (email: string) => users.find((u) => u.email === email)?.id ?? null

    await Booking.createMany([
      {
        bookingNo: '20260520XMIL',
        customerName: 'Anan Wongchai',
        customerPhone: '0812345678',
        customerEmail: 'anan.w@tennis.com',
        customerType: 'member',
        courtId: 1,
        userId: uid('anan.w@tennis.com'),
        bookingDate: '2026-05-20',
        timeStart: '08:00:00',
        timeEnd: '09:00:00',
        totalPrice: 400,
        status: 'confirmed',
        paymentSlip: 'slip01.jpg',
      },
      {
        bookingNo: '20260520QR7K',
        customerName: 'Krittin Suksawat',
        customerPhone: '0823456789',
        customerEmail: 'krittin.s@tennis.com',
        customerType: 'member',
        courtId: 2,
        userId: uid('krittin.s@tennis.com'),
        bookingDate: '2026-05-20',
        timeStart: '09:00:00',
        timeEnd: '10:00:00',
        totalPrice: 400,
        status: 'confirmed',
        paymentSlip: 'slip02.jpg',
      },
      {
        bookingNo: '20260521AB3Z',
        customerName: 'Nattapong Charoenkit',
        customerPhone: '0834567890',
        customerEmail: 'nattapong.c@tennis.com',
        customerType: 'member',
        courtId: 3,
        userId: uid('nattapong.c@tennis.com'),
        bookingDate: '2026-05-21',
        timeStart: '10:00:00',
        timeEnd: '11:00:00',
        totalPrice: 500,
        status: 'confirmed',
        paymentSlip: 'slip03.jpg',
      },
      {
        bookingNo: '20260521TW9P',
        customerName: 'Piyawat Rattanakul',
        customerPhone: '0845678901',
        customerEmail: 'piyawat.r@tennis.com',
        customerType: 'member',
        courtId: 1,
        userId: uid('piyawat.r@tennis.com'),
        bookingDate: '2026-05-21',
        timeStart: '13:00:00',
        timeEnd: '14:00:00',
        totalPrice: 400,
        status: 'confirmed',
        paymentSlip: 'slip04.jpg',
      },
      {
        bookingNo: '20260522LF4N',
        customerName: 'Thanawat Boonmee',
        customerPhone: '0856789012',
        customerEmail: 'thanawat.b@tennis.com',
        customerType: 'member',
        courtId: 2,
        userId: uid('thanawat.b@tennis.com'),
        bookingDate: '2026-05-22',
        timeStart: '15:00:00',
        timeEnd: '16:00:00',
        totalPrice: 400,
        status: 'cancelled',
        paymentSlip: 'slip05.jpg',
      },
      {
        bookingNo: '20260522DK8V',
        customerName: 'Supakorn Limcharoen',
        customerPhone: '0867890123',
        customerEmail: 'supakorn.l@tennis.com',
        customerType: 'member',
        courtId: 3,
        userId: uid('supakorn.l@tennis.com'),
        bookingDate: '2026-05-22',
        timeStart: '16:00:00',
        timeEnd: '17:00:00',
        totalPrice: 500,
        status: 'cancelled',
        paymentSlip: 'slip06.jpg',
      },
      {
        bookingNo: '20260523MR2J',
        customerName: 'Chayut Phromsri',
        customerPhone: '0878901234',
        customerEmail: 'chayut.p@tennis.com',
        customerType: 'member',
        courtId: 1,
        userId: uid('chayut.p@tennis.com'),
        bookingDate: '2026-05-23',
        timeStart: '18:00:00',
        timeEnd: '19:00:00',
        totalPrice: 400,
        status: 'cancelled',
        paymentSlip: 'slip07.jpg',
      },

      // GUEST BOOKINGS
      {
        bookingNo: '20260523YH6S',
        customerName: 'Guest01',
        customerPhone: '0800000001',
        customerEmail: 'guest01@gmail.com',
        customerType: 'guest',
        courtId: 2,
        userId: null,
        bookingDate: '2026-05-23',
        timeStart: '08:00:00',
        timeEnd: '09:00:00',
        totalPrice: 500,
        status: 'confirmed',
        paymentSlip: 'guest-slip01.jpg',
      },
      {
        bookingNo: '20260523CX1B',
        customerName: 'Guest02',
        customerPhone: '0800000002',
        customerEmail: 'guest02@gmail.com',
        customerType: 'guest',
        courtId: 3,
        userId: null,
        bookingDate: '2026-05-23',
        timeStart: '09:00:00',
        timeEnd: '10:00:00',
        totalPrice: 500,
        status: 'confirmed',
        paymentSlip: 'guest-slip02.jpg',
      },
      {
        bookingNo: '20260524WG5E',
        customerName: 'Guest03',
        customerPhone: '0800000003',
        customerEmail: 'guest03@gmail.com',
        customerType: 'guest',
        courtId: 1,
        userId: null,
        bookingDate: '2026-05-24',
        timeStart: '10:00:00',
        timeEnd: '11:00:00',
        totalPrice: 400,
        status: 'confirmed',
        paymentSlip: 'guest-slip03.jpg',
      },
      {
        bookingNo: '20260524NP7T',
        customerName: 'Guest04',
        customerPhone: '0800000004',
        customerEmail: 'guest04@gmail.com',
        customerType: 'guest',
        courtId: 2,
        userId: null,
        bookingDate: '2026-05-24',
        timeStart: '11:00:00',
        timeEnd: '12:00:00',
        totalPrice: 500,
        status: 'cancelled',
        paymentSlip: 'guest-slip04.jpg',
      },
    ])
  }
}
